// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByw0P6lQDUAM520fGa-kZyYb8zXCnKWnc',
    appId: '1:1031118743134:web:4fce5d2bb37bc064ca76cf',
    messagingSenderId: '1031118743134',
    projectId: 'repark-97458',
    authDomain: 'repark-97458.firebaseapp.com',
    databaseURL: 'https://repark-97458-default-rtdb.firebaseio.com',
    storageBucket: 'repark-97458.appspot.com',
    measurementId: 'G-9HYXZ8ZDCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGqz9cmylsMi_r-6pDdD3oSrElBkqKrU',
    appId: '1:1031118743134:android:1a0db7e775ea414cca76cf',
    messagingSenderId: '1031118743134',
    projectId: 'repark-97458',
    databaseURL: 'https://repark-97458-default-rtdb.firebaseio.com',
    storageBucket: 'repark-97458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6Tb_Q6OcWk-UUSs5ZzSEZBV-PqHJ-6M',
    appId: '1:1031118743134:ios:d029d6415cbe5e2aca76cf',
    messagingSenderId: '1031118743134',
    projectId: 'repark-97458',
    databaseURL: 'https://repark-97458-default-rtdb.firebaseio.com',
    storageBucket: 'repark-97458.appspot.com',
    androidClientId:
        '1031118743134-d3l96s6fd8r4umdnr5r8enofq9v5etj9.apps.googleusercontent.com',
    iosClientId:
        '1031118743134-cgt12orpplhq3ag5gmh3gbecpkukss27.apps.googleusercontent.com',
    iosBundleId: 'com.nanreg3.repark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6Tb_Q6OcWk-UUSs5ZzSEZBV-PqHJ-6M',
    appId: '1:1031118743134:ios:d029d6415cbe5e2aca76cf',
    messagingSenderId: '1031118743134',
    projectId: 'repark-97458',
    databaseURL: 'https://repark-97458-default-rtdb.firebaseio.com',
    storageBucket: 'repark-97458.appspot.com',
    androidClientId:
        '1031118743134-d3l96s6fd8r4umdnr5r8enofq9v5etj9.apps.googleusercontent.com',
    iosClientId:
        '1031118743134-cgt12orpplhq3ag5gmh3gbecpkukss27.apps.googleusercontent.com',
    iosBundleId: 'com.nanreg3.repark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByw0P6lQDUAM520fGa-kZyYb8zXCnKWnc',
    appId: '1:1031118743134:web:d20b73cf15a2c33bca76cf',
    messagingSenderId: '1031118743134',
    projectId: 'repark-97458',
    authDomain: 'repark-97458.firebaseapp.com',
    databaseURL: 'https://repark-97458-default-rtdb.firebaseio.com',
    storageBucket: 'repark-97458.appspot.com',
    measurementId: 'G-M96P1YEZEY',
  );
}
